/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bangundatar_202557201001;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class Beranda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Beranda.class.getName());

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSegitiga = new javax.swing.JButton();
        btnPersegiPanjang = new javax.swing.JButton();
        btnLingkaran = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnPersegi = new javax.swing.JButton();
        btnJajarGenjang = new javax.swing.JButton();
        btnTrapesium = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beranda");
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLIKASI BANGUN DATAR");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnSegitiga.setText("Segitiga");
        btnSegitiga.addActionListener(this::btnSegitigaActionPerformed);

        btnPersegiPanjang.setText("Persegi Panjang");
        btnPersegiPanjang.addActionListener(this::btnPersegiPanjangActionPerformed);

        btnLingkaran.setText("Lingkaran");
        btnLingkaran.addActionListener(this::btnLingkaranActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        btnPersegi.setText("Persegi");
        btnPersegi.addActionListener(this::btnPersegiActionPerformed);

        btnJajarGenjang.setText("Jajar Genjang");
        btnJajarGenjang.addActionListener(this::btnJajarGenjangActionPerformed);

        btnTrapesium.setText("Trapesium");
        btnTrapesium.addActionListener(this::btnTrapesiumActionPerformed);

        btnAbout.setText("About");
        btnAbout.addActionListener(this::btnAboutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnSegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLingkaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPersegiPanjang, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPersegi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJajarGenjang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrapesium, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPersegi)
                    .addComponent(btnSegitiga))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJajarGenjang)
                    .addComponent(btnPersegiPanjang))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLingkaran)
                    .addComponent(btnTrapesium))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluar)
                    .addComponent(btnAbout))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        btnKeluar.setText("Menutup...");
        btnKeluar.setEnabled(false);
        
        javax.swing.Timer timer = new javax.swing.Timer(500, (e) -> {
        // Pilih salah satu diantara 3 dibawah
        System.exit(0);
        // Dispose();
        // setVisible(false)
    });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegitigaActionPerformed
        // TODO add your handling code here:
        btnSegitiga.setEnabled(false);
        btnSegitiga.setText("Loading...");
        javax.swing.Timer timer = new javax.swing.Timer(500, (e) -> {
        new Segitiga().setVisible(true);
        // new Segitiga().setVisible(false);
         dispose();
});

        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnSegitigaActionPerformed

    private void btnPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersegiActionPerformed
        // TODO add your handling code here:
        btnPersegi.setEnabled(false);
        btnPersegi.setText("Loading...");
        javax.swing.Timer timer = new javax.swing.Timer(500, (e) -> {
        new Persegi().setVisible(true);
        dispose();
});

        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnPersegiActionPerformed

    private void btnPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersegiPanjangActionPerformed
        // TODO add your handling code here:
        btnPersegiPanjang.setEnabled(false);
        btnPersegiPanjang.setText("Loading...");
        javax.swing.Timer timer = new javax.swing.Timer(500, (e) -> {
        new PersegiPanjang().setVisible(true);
        dispose();
});

        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnPersegiPanjangActionPerformed

    private void btnJajarGenjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJajarGenjangActionPerformed
        // TODO add your handling code here:
        btnJajarGenjang.setEnabled(false);
        btnJajarGenjang.setText("Loading...");
        javax.swing.Timer timer = new javax.swing.Timer(500, (e) -> {
        new JajarGenjang().setVisible(true);
        dispose();
});

        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnJajarGenjangActionPerformed

    private void btnLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLingkaranActionPerformed
        // TODO add your handling code here:
        btnLingkaran.setEnabled(false);
        btnLingkaran.setText("Loading...");
        javax.swing.Timer timer = new javax.swing.Timer(500, (e) -> {
        new Lingkaran().setVisible(true);
        dispose();
});

        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnLingkaranActionPerformed

    private void btnTrapesiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrapesiumActionPerformed
        // TODO add your handling code here:
        btnTrapesium.setEnabled(false);
        btnTrapesium.setText("Loading...");
        javax.swing.Timer timer = new javax.swing.Timer(500, (e) -> {
        new Trapesium().setVisible(true);
        dispose();
});

        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnTrapesiumActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        btnAbout.setEnabled(false);
        btnAbout.setText("Loading...");
        javax.swing.Timer timer = new javax.swing.Timer(500, (e) -> {
        new About().setVisible(true);
        dispose();
});

        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Beranda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnJajarGenjang;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnLingkaran;
    private javax.swing.JButton btnPersegi;
    private javax.swing.JButton btnPersegiPanjang;
    private javax.swing.JButton btnSegitiga;
    private javax.swing.JButton btnTrapesium;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
